import { useEffect, useRef, useState } from 'react'
import type { ChangeEvent } from 'react'
import './App.css'

type Status = 'idle' | 'ready' | 'denied' | 'unsupported' | 'error'
const sample = 'Welcome to your calm space for clear ideas.\n\nTake a breath. Look at the lens. Let each sentence land.\n\nThis teleprompter keeps the words moving smoothly while you focus on your message.'
const initial = { text: sample, speed: 34, size: 30, leading: 1.55, width: 720, align: 'center', mirror: false }

export default function App() {
  const [settings, setSettings] = useState(() => { try { return { ...initial, ...JSON.parse(localStorage.getItem('prompt-settings') || '{}') } } catch { return initial } })
  const [playing, setPlaying] = useState(false); const [editor, setEditor] = useState(false); const [panel, setPanel] = useState(true)
  const [countdown, setCountdown] = useState<number | null>(null); const [camera, setCamera] = useState<Status>('idle'); const [mic, setMic] = useState<Status>('idle')
  const [recording, setRecording] = useState(false); const [facing, setFacing] = useState<'user'|'environment'>('user'); const [wake, setWake] = useState(false)
  const [notice, setNotice] = useState('Everything stays on this device.'); const [progress, setProgress] = useState(0)
  const view = useRef<HTMLDivElement>(null); const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null); const recorder = useRef<MediaRecorder | null>(null); const lock = useRef<WakeLockSentinel | null>(null); const raf = useRef(0); const last = useRef(0); const hide = useRef(0)
  const set = <K extends keyof typeof settings>(key: K, value: (typeof settings)[K]) => setSettings((x: typeof settings) => ({ ...x, [key]: value }))
  const stop = () => { stream.current?.getTracks().forEach(t => t.stop()); stream.current = null; if (video.current) video.current.srcObject = null }

  useEffect(() => { localStorage.setItem('prompt-settings', JSON.stringify(settings)) }, [settings])
  useEffect(() => () => { cancelAnimationFrame(raf.current); stop(); lock.current?.release().catch(() => undefined) }, [])
  useEffect(() => { const pause = () => { if (document.hidden) setPlaying(false) }; document.addEventListener('visibilitychange', pause); return () => document.removeEventListener('visibilitychange', pause) }, [])
  useEffect(() => { const tick = (now: number) => { if (playing && view.current) { const max = Math.max(1, view.current.scrollHeight - view.current.clientHeight); const next = Math.min(max, view.current.scrollTop + ((now - (last.current || now)) / 1000) * settings.speed); view.current.scrollTop = next; setProgress(next / max * 100); if (next >= max) setPlaying(false); last.current = now } else last.current = 0; raf.current = requestAnimationFrame(tick) }; raf.current = requestAnimationFrame(tick); return () => cancelAnimationFrame(raf.current) }, [playing, settings.speed])
  useEffect(() => { if (countdown === null) return; const id = setTimeout(() => { if (countdown <= 1) { setCountdown(null); setPlaying(true) } else setCountdown(countdown - 1) }, 1000); return () => clearTimeout(id) }, [countdown])
  const reveal = () => { setPanel(true); clearTimeout(hide.current); hide.current = window.setTimeout(() => setPanel(false), 3400) }
  const start = () => { if (!settings.text.trim()) { setEditor(true); setNotice('Add your script before starting.'); return }; setCountdown(3) }
  const restart = () => { if (view.current) view.current.scrollTop = 0; setPlaying(false); setProgress(0) }
  const file = (e: ChangeEvent<HTMLInputElement>) => { const f = e.target.files?.[0]; if (!f || !/\.(txt|md)$/i.test(f.name)) return setNotice('Choose a .txt or .md file.'); const r = new FileReader(); r.onload = () => { set('text', String(r.result || '')); setEditor(false); setNotice('Script imported locally.') }; r.readAsText(f) }

  const media = async (audio = false) => { if (!navigator.mediaDevices?.getUserMedia) { setCamera('unsupported'); setNotice('Media needs HTTPS or localhost in a supported browser.'); return }; try { stop(); const s = await navigator.mediaDevices.getUserMedia({ video: { facingMode: facing }, audio }); stream.current = s; if (video.current) { video.current.srcObject = s; await video.current.play() }; setCamera('ready'); setMic(audio ? 'ready' : 'idle'); setNotice('Camera ready. Nothing is uploaded.') } catch (e) { const denied = e instanceof DOMException && e.name === 'NotAllowedError'; setCamera(denied ? 'denied' : 'error'); if (audio) setMic(denied ? 'denied' : 'error'); setNotice(denied ? 'Permission was blocked. Enable it in browser settings, then retry.' : 'Could not access the device; it may be busy or unavailable.') } }
  const cameraToggle = () => { if (stream.current) { stop(); setCamera('idle'); setMic('idle'); setRecording(false); setNotice('Camera stopped.') } else void media(false) }
  const micToggle = async () => { const t = stream.current?.getAudioTracks()[0]; if (t) { t.enabled = !t.enabled; setMic(t.enabled ? 'ready' : 'idle') } else await media(true) }
  const record = async () => { if (recording && recorder.current) return recorder.current.stop(); if (!stream.current) await media(true); if (!stream.current || !window.MediaRecorder) return setNotice('Recording is unavailable in this browser.'); const chunks: Blob[] = []; const r = new MediaRecorder(stream.current); r.ondataavailable = e => e.data.size && chunks.push(e.data); r.onstop = () => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(chunks, { type: r.mimeType })); a.download = `teleprompter-${Date.now()}.webm`; a.click(); setRecording(false); setNotice('Recording downloaded locally.') }; r.start(1000); recorder.current = r; setRecording(true); setNotice('Recording locally…') }
  const wakeToggle = async () => { try { if (lock.current) { await lock.current.release(); lock.current = null; return setWake(false) }; if (!('wakeLock' in navigator)) throw Error(); lock.current = await navigator.wakeLock.request('screen'); lock.current.addEventListener('release', () => setWake(false)); setWake(true); setNotice('Screen will stay awake while this tab is active.') } catch { setNotice('Wake lock is unavailable here; keep the screen awake manually.') } }
  const fullscreen = async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await document.documentElement.requestFullscreen() } catch { setNotice('Fullscreen is unavailable in this browser.') } }

  return <main className="app" onPointerMove={reveal} onPointerDown={reveal}>
    <header><button className="brand" onClick={() => setEditor(true)}>● PROMPT</button><small><i className={recording ? 'live' : ''}/>{recording ? 'REC' : playing ? 'READING' : 'READY'}</small><button className="text-btn" onClick={fullscreen}>⛶ Fullscreen</button></header>
    {camera === 'ready' && <aside className="camera"><video ref={video} muted playsInline/><em>{recording ? '● Recording' : 'Camera preview'}</em><button onClick={async () => { setFacing(x => x === 'user' ? 'environment' : 'user'); await media(mic === 'ready') }}>↻</button></aside>}
    <section className="prompter" onClick={() => playing && setPlaying(false)}><div className="script" ref={view} style={{ '--size': settings.size + 'px', '--leading': settings.leading, '--width': settings.width + 'px', textAlign: settings.align, transform: settings.mirror ? 'scaleX(-1)' : undefined } as React.CSSProperties}>{settings.text.split('\n').map((x: string, i: number) => <p key={i}>{x || ' '}</p>)}</div><div className="focus"/><div className="progress"><b style={{ width: progress + '%' }}/></div></section>
    {countdown !== null && <div className="countdown">{countdown || 'Go'}</div>}
    {panel && <section className="dock"><div className="primary"><button onClick={restart}>↺</button><button className="play" onClick={() => playing ? setPlaying(false) : start()}>{playing ? 'Ⅱ Pause' : '▶ Start'}</button><button onClick={() => set('speed', Math.min(100, settings.speed + 5))}>＋</button></div><div className="quick"><label>Speed <input type="range" min="8" max="100" value={settings.speed} onChange={e => set('speed', +e.target.value)}/><b>{settings.speed}</b></label><button className={wake ? 'on' : ''} onClick={wakeToggle}>☀ Awake</button><button className={camera === 'ready' ? 'on' : ''} onClick={cameraToggle}>◉ Camera</button><button className={mic === 'ready' ? 'on' : ''} onClick={micToggle}>◌ Mic</button><button className={recording ? 'rec' : ''} onClick={record}>{recording ? '■ Stop' : '● Record'}</button></div><details><summary>Reading settings</summary><div className="settings"><label>Text<input type="range" min="20" max="62" value={settings.size} onChange={e => set('size', +e.target.value)}/></label><label>Spacing<input type="range" min="1.2" max="2.2" step=".05" value={settings.leading} onChange={e => set('leading', +e.target.value)}/></label><label>Width<input type="range" min="280" max="960" step="10" value={settings.width} onChange={e => set('width', +e.target.value)}/></label><div><button onClick={() => set('align','left')}>≡</button><button onClick={() => set('align','center')}>≡</button><button onClick={() => set('align','right')}>≡</button><button onClick={() => set('mirror', !settings.mirror)}>↔ Mirror</button></div></div></details></section>}
    <p className="notice">{notice}</p>
    {editor && <div className="modal"><section><div className="editor-head"><div><small>YOUR SCRIPT</small><h1>Make the message yours.</h1></div><button onClick={() => setEditor(false)}>×</button></div><textarea autoFocus value={settings.text} onChange={e => set('text',e.target.value)} placeholder="Paste your script here…"/><footer><label>Import .txt or .md<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={file}/></label><span>{settings.text.trim().split(/\s+/).filter(Boolean).length} words</span><button className="done" onClick={() => { setEditor(false); setNotice('Script saved locally. Ready when you are.') }}>Done</button></footer></section></div>}
  </main>
}
